In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dfCompetition = pd.read_csv('../Dataset/dfFinalCompetition2025.csv')
old_suffix = '_Winner'
new_suffix = 'Cup'
dfCompetition.columns = [col[:-len(old_suffix)] + new_suffix if col.endswith(old_suffix) else col for col in dfCompetition.columns]

nazionality = [
    "Inghilterra",  # 1
    "Spagna",       # 2
    "Francia",      # 3
    "Spagna",       # 4
    "Inghilterra",  # 5
    "Inghilterra",  # 6
    "Francia",      # 7
    "Francia",      # 8
    "Germania",     # 9
    "Francia",      # 10
    "Spagna",       # 11
    "Francia",      # 12
    "Inghilterra",  # 13
    "Spagna",       # 14
    "Ungheria",     # 15
    "Germania",     # 16
    "Italia",       # 17
    "Spagna",       # 18
    "Inghilterra",  # 19
    "Repubblica Ceca",  # 20
    "Portogallo",   # 21
    "Germania",     # 22
    "Russia",       # 23
    "Italia",       # 24
    "Inghilterra",  # 25
    "Scozia",       # 26
    "Spagna",       # 27
    "Spagna",       # 28
    "Portogallo",   # 29
    "Italia",       # 30
    "Spagna",       # 31
    "Inghilterra",  # 32
    "Portogallo",   # 33
    "Germania",     # 34
    "Ungheria",     # 35
    "Inghilterra",  # 36
    "Scozia",       # 37
    "Irlanda del Nord",  # 38
    "Inghilterra",  # 39
    "Serbia",       # 40
    "Italia",       # 41
    "Italia",       # 42
    "Germania",     # 43
    "Germania",     # 44
    "Inghilterra",  # 45
    "Italia",       # 46
    "Olanda",  # 47
    "Italia",       # 48
    "Irlanda del Nord",  # 49
    "Germania",     # 50
    "Germania",     # 51
    "Germania",     # 52
    "Olanda",  # 53
    "Italia",       # 54
    "Germania",     # 55
    "Olanda",  # 56
    "Germania",     # 57
    "Polonia",      # 58
    "Ucraina",      # 59
    "Germania",     # 60
    "Olanda",  # 61
    "Germania",     # 62
    "Olanda",  # 63
    "Repubblica Ceca",  # 64
    "Danimarca",    # 65
    "Inghilterra",  # 66
    "Francia",      # 67
    "Inghilterra",  # 68
    "Austria",      # 69
    "Olanda",  # 70
    "Inghilterra",  # 71
    "Germania",     # 72
    "Olanda",  # 73
    "Germania",     # 74
    "Germania",     # 75
    "Francia",      # 76
    "Germania",     # 77
    "Germania",     # 78
    "Germania",     # 79
    "Italia",       # 80
    "Francia",      # 81
    "Polonia",      # 82
    "Francia",      # 83
    "Scozia",       # 84
    "Danimarca",    # 85
    "Francia",      # 86
    "Francia",      # 87
    "Danimarca",    # 88
    "Francia",      # 89
    "Danimarca",    # 90
    "Germania",     # 91
    "Ucraina",      # 92
    "Inghilterra",  # 93
    "Spagna",       # 94
    "Olanda",  # 95
    "Portogallo",   # 96
    "Spagna",       # 97
    "Olanda",  # 98
    "Olanda",  # 99
    "Olanda",  # 100
    "Olanda",  # 101
    "Italia",       # 102
    "Olanda",  # 103
    "Germania",     # 104
    "Italia",       # 105
    "Germania",     # 106
    "Francia",      # 107
    "Montenegro",   # 108
    "Macedonia del Nord",  # 109
    "Germania",     # 110
    "Olanda",  # 111
    "Bulgaria",     # 112
    "Olanda",  # 113
    "Italia",       # 114
    "Olanda",  # 115
    "Francia",      # 116
    "Bulgaria",     # 117
    "Italia",       # 118
    "Italia",       # 119
    "Liberia",      # 120
    "Germania",     # 121
    "Finlandia",    # 122
    "Germania",     # 123
    "Portogallo",   # 124
    "Inghilterra",  # 125
    "Portogallo",   # 126
    "Montenegro",   # 127
    "Francia",      # 128
    "Francia",      # 129
    "Croazia",      # 130
    "Portogallo",   # 131
    "Brasile",      # 132
    "Inghilterra",  # 133
    "Ucraina",      # 134
    "Portogallo",   # 135
    "Francia",      # 136
    "Ucraina",      # 137
    "Inghilterra",  # 138
    "Spagna",       # 139
    "Germania",     # 140
    "Portogallo",   # 141
    "Brasile",      # 142
    "Germania",     # 143
    "Repubblica Ceca",  # 144
    "Francia",      # 145
    "Italia",       # 146
    "Ucraina",      # 147
    "Portogallo",   # 148
    "Brasile",      # 149
    "Brasile",      # 150
    "Inghilterra",  # 151
    "Inghilterra",  # 152
    "Italia",       # 153
    "Italia",       # 154
    "Francia",      # 155
    "Brasile",      # 156
    "Portogallo",   # 157
    "Argentina",    # 158
    "Portogallo",   # 159
    "Argentina",    # 160
    "Spagna",       # 161
    "Argentina",    # 162
    "Portogallo",   # 163
    "Spagna",       # 164
    "Argentina",    # 165
    "Spagna",       # 166
    "Spagna",       # 167
    "Argentina",    # 168
    "Portogallo",   # 169
    "Spagna",       # 170
    "Argentina",    # 171
    "Portogallo",   # 172
    "Spagna",       # 173
    "Portogallo",   # 174
    "Argentina",    # 175
    "Francia",      # 176
    "Portogallo",   # 177
    "Argentina",    # 178
    "Germania",     # 179
    "Argentina",    # 180
    "Portogallo",   # 181
    "Brasile",      # 182
    "Portogallo",   # 183
    "Argentina",    # 184
    "Francia",      # 185
    "Portogallo",   # 186
    "Argentina",    # 187
    "Brasile",      # 188
    "Croazia",      # 189
    "Portogallo",   # 190
    "Francia",      # 191
    "Argentina",    # 192
    "Olanda",       # 193
    "Portogallo",   # 194
    "Argentina",    # 195
    "Polonia",      # 196
    "Italia",       # 197
    "Francia",      # 198
    "Senegal",      # 199
    "Belgio",       # 200
    "Argentina",    # 201
    "Norvegia",     # 202
    "Francia",      # 203
    "Spagna",       # 204
    "Brasile",      # 205
    "Inghilterra"   # 206
]
dfCompetition['nazionality'] = nazionality
for col in dfCompetition.columns:
    dfCompetition[col] = dfCompetition[col].replace('Barcelona', 'Barcellona')

dfCompetition.at[51, 'rank'] = '3rd' 
dfCompetition.at[108, 'rank'] = '3rd'
dfCompetition.drop(index=[6, 109], inplace=True)
display(dfCompetition)
dfCompetition.to_csv('../Dataset/dfPlayerFinal_2025.csv', index=False)
dfCompetition.reset_index(drop=True, inplace=True)

dfCoppe = pd.read_csv('../Dataset/dfUnioneCoppe2025.csv')
dfCoppe.columns = [col[:-len(old_suffix)] + new_suffix if col.endswith(old_suffix) else col for col in dfCoppe.columns]

for col in dfCoppe.columns:
    dfCoppe[col] = dfCoppe[col].replace('Inter', 'Internazionale')
dfCoppe = dfCoppe[dfCoppe['year'] != 2020].reset_index(drop=True)
dfCoppe = dfCoppe.drop_duplicates(subset='year')

,year,rank,player,team,points,percentages,nazionality,role,age,competitionTeam
0,1956,1st,Stanley Matthews,Blackpool,47.0,37.90,Inghilterra,RW,41,Premier League
1,1956,2nd,Alfredo Di Stéfano,Real Madrid,44.0,35.48,Spagna,SS,30,La Liga
2,1956,3rd,Raymond Kopa,Real Madrid,33.0,26.61,Francia,RW,25,La Liga
3,1957,1st,Alfredo Di Stéfano,Real Madrid,72.0,58.54,Spagna,SS,31,La Liga
4,1957,2nd,Billy Wright,Wolverhampton Wanderers,19.0,15.45,Inghilterra,CB,33,Premier League
...,...,...,...,...,...,...,...,...,...,...
201,2023,2nd,Erling Haaland,Manchester City,357.0,32.78,Norvegia,CF,23,Premier League
202,2023,3rd,Kylian Mbappé,Paris Saint-Germain,270.0,24.79,Francia,CF,25,Ligue1
203,2024,1st,Rodri,Manchester City,1170.0,36.38,Spagna,DM,28,Premier League
204,2024,2nd,Vinícius Júnior,Real Madrid,1129.0,35.11,Brasile,LW,24,La Liga
205,2024,3rd,Jude Bellingham,Real Madrid,917.0,28.51,Inghilterra,AM,21,La Liga

In [3]:
dfFirstRank = pd.DataFrame()
dfFirstRank = dfCompetition[dfCompetition['rank'] == '1st'][['year','rank', 'player', 'team', 'nazionality']]
dfFirstRank.reset_index(drop=True, inplace=True)
dfFirstRank = dfFirstRank.drop_duplicates(subset='year')
display(dfFirstRank)

    year rank                  player                 team  nazionality
0   1956  1st        Stanley Matthews            Blackpool  Inghilterra
1   1957  1st      Alfredo Di Stéfano          Real Madrid       Spagna
2   1958  1st            Raymond Kopa          Real Madrid      Francia
3   1959  1st      Alfredo Di Stéfano          Real Madrid       Spagna
4   1960  1st  Luis Suárez Miramontes           Barcellona       Spagna
..   ...  ...                     ...                  ...          ...
63  2019  1st            Lionel Messi           Barcellona    Argentina
64  2021  1st            Lionel Messi           Barcellona    Argentina
65  2022  1st           Karim Benzema          Real Madrid      Francia
66  2023  1st            Lionel Messi  Paris Saint-Germain    Argentina
67  2024  1st                   Rodri      Manchester City       Spagna

[68 rows x 5 columns]

In [4]:
def colonna_presente(df, colonna):
    return colonna in df.columns

In [5]:
dfFirstRankCup = pd.DataFrame(dfFirstRank)
count = 0
for (_, row1), (_, row2) in zip(dfFirstRank.iterrows(), dfCoppe.iterrows()):
    team_name = row1['team']
    nazionality_name = row1['nazionality']
    for col in dfCoppe.columns:
        if row2[col] == team_name:
            if not colonna_presente(dfFirstRankCup, col):
                dfFirstRankCup[col] = None
            dfFirstRankCup.loc[count, col] = team_name
        if row2[col] == nazionality_name:
            if not colonna_presente(dfFirstRankCup, col):
                dfFirstRankCup[col] = None 
            dfFirstRankCup.loc[count, col] = nazionality_name

    count += 1

display(dfFirstRankCup)

,year,rank,player,team,nazionality,championsCup,laLigaCup,serieACup,primeraLigaCup,MondialeCup,coppaOlandaCup,coppaItaliaCup,EuropeoCup,europaLeagueCup,bundesligaCup,CoppaAmericaCup,coppaInghilterraCup,coppaSpagnaCup,legue1Cup,premierLeagueCup
0,1956,1st,Stanley Matthews,Blackpool,Inghilterra,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,1957,1st,Alfredo Di Stéfano,Real Madrid,Spagna,Real Madrid,Real Madrid,None,None,None,None,None,None,None,None,None,None,None,None,None
2,1958,1st,Raymond Kopa,Real Madrid,Francia,Real Madrid,Real Madrid,None,None,None,None,None,None,None,None,None,None,None,None,None
3,1959,1st,Alfredo Di Stéfano,Real Madrid,Spagna,Real Madrid,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,1960,1st,Luis Suárez Miramontes,Barcellona,Spagna,None,Barcellona,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,2019,1st,Lionel Messi,Barcellona,Argentina,None,Barcellona,None,None,None,None,None,None,None,None,None,None,None,None,None
64,2021,1st,Lionel Messi,Barcellona,Argentina,None,None,None,None,None,None,None,None,None,None,Argentina,None,Barcellona,None,None
65,2022,1st,Karim Benzema,Real Madrid,Francia,Real Madrid,Real Madrid,None,None,None,None,None,None,None,None,None,None,None,None,None
66,2023,1st,Lionel Messi,Paris Saint-Germain,Argentina,None,None,None,None,None,None,None,None,None,None,None,None,None,Paris Saint-Germain,None
67,2024,1st,Rodri,Manchester City,Spagna,None,None,None,None,None,None,None,Spagna,None,None,None,None,None,None,Manchester City

In [6]:
dfSecondtRank = pd.DataFrame()
dfSecondtRank = dfCompetition[dfCompetition['rank'] == '2nd'][['year','rank', 'player', 'team', 'nazionality']]
dfSecondtRank.reset_index(drop=True, inplace=True)

dfSecondtRankCup = pd.DataFrame(dfSecondtRank)
count = 0
for (_, row1), (_, row2) in zip(dfSecondtRankCup.iterrows(), dfCoppe.iterrows()):
    team_name = row1['team']
    nazionality_name = row1['nazionality']
    for col in dfCoppe.columns:
        if row2[col] == team_name:
            if not colonna_presente(dfSecondtRankCup, col):
                dfSecondtRankCup[col] = None
            dfSecondtRankCup.loc[count, col] = team_name
        if row2[col] == nazionality_name:
            if not colonna_presente(dfSecondtRankCup, col):
                dfSecondtRankCup[col] = None 
            dfSecondtRankCup.loc[count, col] = nazionality_name
    count += 1
display(dfSecondtRankCup)

,year,rank,player,team,nazionality,championsCup,EuropeoCup,serieACup,coppaBelgioCup,coppaSpagnaCup,premierLeagueCup,europaLeagueCup,coppaItaliaCup,laLigaCup,MondialeCup,coppaInghilterraCup
0,1956,2nd,Alfredo Di Stéfano,Real Madrid,Spagna,Real Madrid,None,None,None,None,None,None,None,None,None,None
1,1957,2nd,Billy Wright,Wolverhampton Wanderers,Inghilterra,None,None,None,None,None,None,None,None,None,None,None
2,1958,2nd,Helmut Rahn,Rot-Weiss Essen,Germania,None,None,None,None,None,None,None,None,None,None,None
3,1959,2nd,Raymond Kopa,Real Madrid,Francia,Real Madrid,None,None,None,None,None,None,None,None,None,None
4,1960,2nd,Ferenc Puskás,Real Madrid,Ungheria,Real Madrid,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,2019,2nd,Virgil van Dijk,Liverpool,Olanda,Liverpool,None,None,None,None,None,None,None,None,None,None
64,2021,2nd,Robert Lewandowski,Bayern Munich,Polonia,None,None,None,None,None,None,None,None,None,None,None
65,2022,2nd,Sadio Mané,Liverpool,Senegal,None,None,None,None,None,None,None,None,None,None,Liverpool
66,2023,2nd,Erling Haaland,Manchester City,Norvegia,Manchester City,None,None,None,None,Manchester City,None,None,None,None,Manchester City
67,2024,2nd,Vinícius Júnior,Real Madrid,Brasile,Real Madrid,None,None,None,None,None,None,None,Real Madrid,None,None

In [7]:
dfThrerdRank = pd.DataFrame()
dfThrerdRank = dfCompetition[dfCompetition['rank'] == '3rd'][['year','rank', 'player', 'team', 'nazionality']]
dfThrerdRank.reset_index(drop=True, inplace=True)
dfThrerdRank = dfThrerdRank.drop_duplicates(subset='year')

def colonna_presente(df, colonna):
    return colonna in df.columns

dfThrerdRankCup = pd.DataFrame(dfThrerdRank)
count = 0
for (_, row1), (_, row2) in zip(dfThrerdRankCup.iterrows(), dfCoppe.iterrows()):
    team_name = row1['team']
    nazionality_name = row1['nazionality']
    for col in dfCoppe.columns:
        if row2[col] == team_name:
            if not colonna_presente(dfThrerdRankCup, col):
                dfThrerdRankCup[col] = None
            dfThrerdRankCup.loc[count, col] = team_name
        if row2[col] == nazionality_name:
            if not colonna_presente(dfThrerdRankCup, col):
                dfThrerdRankCup[col] = None  
            dfThrerdRankCup.loc[count, col] = nazionality_name
    count += 1
display(dfThrerdRankCup)

,year,rank,player,team,nazionality,championsCup,coppaItaliaCup,EuropeoCup,laLigaCup,serieACup,scottishPremiershipCup,coppaScoziaCup,coppaOlandaCup,coppaSpagnaCup,europaLeagueCup,CoppaAmericaCup,MondialeCup,coppaFranciaCup,premierLeagueCup,legue1Cup
0,1956,3rd,Raymond Kopa,Real Madrid,Francia,Real Madrid,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,1957,3rd,Duncan Edwards,Manchester United,Inghilterra,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,1958,3rd,Just Fontaine,Stade de Reims,Francia,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,1959,3rd,John Charles,Juventus,Inghilterra,None,Juventus,None,None,None,None,None,None,None,None,None,None,None,None,None
4,1960,3rd,Uwe Seeler,Hamburg,Germania,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,2019,3rd,Cristiano Ronaldo,Juventus,Portogallo,None,None,None,None,Juventus,None,None,None,None,None,None,None,None,None,None
64,2021,3rd,Jorginho,Chelsea,Italia,Chelsea,None,None,None,None,None,None,None,None,None,None,None,None,None,None
65,2022,3rd,Kevin De Bruyne,Manchester City,Belgio,None,None,None,None,None,None,None,None,None,None,None,None,None,Manchester City,None
66,2023,3rd,Kylian Mbappé,Paris Saint-Germain,Francia,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Paris Saint-Germain
67,2024,3rd,Jude Bellingham,Real Madrid,Inghilterra,Real Madrid,None,None,Real Madrid,None,None,None,None,None,None,None,None,None,None,None

In [8]:
dfTrophies = pd.DataFrame()
dfTrophies = pd.concat([dfFirstRankCup, dfSecondtRankCup, dfThrerdRankCup], ignore_index=True)
dfTrophies = dfTrophies.sort_values(by=['year', 'rank'])
dfTrophies.reset_index(drop=True, inplace=True)
dfTrophies.columns = dfTrophies.columns.str.replace('Cup', '', regex=False)
display(dfTrophies)
dfTrophies.to_csv('../Dataset/dfPlayerTrophies_2025.csv', index=False)

,year,rank,player,team,nazionality,champions,laLiga,serieA,primeraLiga,Mondiale,...,bundesliga,CoppaAmerica,coppaInghilterra,coppaSpagna,legue1,premierLeague,coppaBelgio,scottishPremiership,coppaScozia,coppaFrancia
0,1956,1st,Stanley Matthews,Blackpool,Inghilterra,None,None,None,None,None,...,None,None,None,None,None,None,NaN,NaN,NaN,NaN
1,1956,2nd,Alfredo Di Stéfano,Real Madrid,Spagna,Real Madrid,None,None,NaN,None,...,NaN,NaN,None,None,NaN,None,None,NaN,NaN,NaN
2,1956,3rd,Raymond Kopa,Real Madrid,Francia,Real Madrid,None,None,NaN,None,...,NaN,None,NaN,None,None,None,NaN,None,None,None
3,1957,1st,Alfredo Di Stéfano,Real Madrid,Spagna,Real Madrid,Real Madrid,None,None,None,...,None,None,None,None,None,None,NaN,NaN,NaN,NaN
4,1957,2nd,Billy Wright,Wolverhampton Wanderers,Inghilterra,None,None,None,NaN,None,...,NaN,NaN,None,None,NaN,None,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,2023,2nd,Erling Haaland,Manchester City,Norvegia,Manchester City,None,None,NaN,None,...,NaN,NaN,Manchester City,None,NaN,Manchester City,None,NaN,NaN,NaN
200,2023,3rd,Kylian Mbappé,Paris Saint-Germain,Francia,None,None,None,NaN,None,...,NaN,None,NaN,None,Paris Saint-Germain,None,NaN,None,None,None
201,2024,1st,Rodri,Manchester City,Spagna,None,None,None,None,None,...,None,None,None,None,None,Manchester City,NaN,NaN,NaN,NaN
202,2024,2nd,Vinícius Júnior,Real Madrid,Brasile,Real Madrid,Real Madrid,None,NaN,None,...,NaN,NaN,None,None,NaN,None,None,NaN,NaN,NaN
203,2024,3rd,Jude Bellingham,Real Madrid,Inghilterra,Real Madrid,Real Madrid,None,NaN,None,...,NaN,None,NaN,None,None,None,NaN,None,None,None

In [11]:
for _, row in dfTrophies.iterrows():
    for col in dfTrophies.columns[5:]:
        if pd.notna(row[col]):
            if row[col] is not None:
                 dfTrophies.at[row.name, col] = col
display(dfTrophies)
dfTrophies.to_csv('../Dataset/dfPlayerTrophiesWinner_2025.csv', index=False)

,year,rank,player,team,nazionality,champions,laLiga,serieA,primeraLiga,Mondiale,...,bundesliga,CoppaAmerica,coppaInghilterra,coppaSpagna,legue1,premierLeague,coppaBelgio,scottishPremiership,coppaScozia,coppaFrancia
0,1956,1st,Stanley Matthews,Blackpool,Inghilterra,None,None,None,None,None,...,None,None,None,None,None,None,NaN,NaN,NaN,NaN
1,1956,2nd,Alfredo Di Stéfano,Real Madrid,Spagna,champions,None,None,NaN,None,...,NaN,NaN,None,None,NaN,None,None,NaN,NaN,NaN
2,1956,3rd,Raymond Kopa,Real Madrid,Francia,champions,None,None,NaN,None,...,NaN,None,NaN,None,None,None,NaN,None,None,None
3,1957,1st,Alfredo Di Stéfano,Real Madrid,Spagna,champions,laLiga,None,None,None,...,None,None,None,None,None,None,NaN,NaN,NaN,NaN
4,1957,2nd,Billy Wright,Wolverhampton Wanderers,Inghilterra,None,None,None,NaN,None,...,NaN,NaN,None,None,NaN,None,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,2023,2nd,Erling Haaland,Manchester City,Norvegia,champions,None,None,NaN,None,...,NaN,NaN,coppaInghilterra,None,NaN,premierLeague,None,NaN,NaN,NaN
200,2023,3rd,Kylian Mbappé,Paris Saint-Germain,Francia,None,None,None,NaN,None,...,NaN,None,NaN,None,legue1,None,NaN,None,None,None
201,2024,1st,Rodri,Manchester City,Spagna,None,None,None,None,None,...,None,None,None,None,None,premierLeague,NaN,NaN,NaN,NaN
202,2024,2nd,Vinícius Júnior,Real Madrid,Brasile,champions,laLiga,None,NaN,None,...,NaN,NaN,None,None,NaN,None,None,NaN,NaN,NaN
203,2024,3rd,Jude Bellingham,Real Madrid,Inghilterra,champions,laLiga,None,NaN,None,...,NaN,None,NaN,None,None,None,NaN,None,None,None