In [1]:
import pandas as pd
df = pd.read_csv('dfFinalCompetition2025.csv')
df_Champions_EuropaLeague = pd.read_csv('datasetChampionEuropaLeague.csv')
df_CompetizioniNazionali = pd.read_csv('datasetCompetizioniNazioneali.csv')
df_CompetizioniPerNazione = pd.read_csv('datasetCompetizioniPerNazione.csv')

display(df)
display(df_Champions_EuropaLeague)
display(df_CompetizioniNazionali)
display(df_CompetizioniPerNazione)

,year,rank,player,team,points,percentages,nazionality,role,age,competitionTeam
0,1956,1st,Stanley Matthews,Blackpool,47.0,37.90,England,RW,41,Premier League
1,1956,2nd,Alfredo Di Stéfano,Real Madrid,44.0,35.48,Spain,SS,30,La Liga
2,1956,3rd,Raymond Kopa,Real Madrid,33.0,26.61,France,RW,25,La Liga
3,1957,1st,Alfredo Di Stéfano,Real Madrid,72.0,58.54,Spain,SS,31,La Liga
4,1957,2nd,Billy Wright,Wolverhampton Wanderers,19.0,15.45,England,CB,33,Premier League
...,...,...,...,...,...,...,...,...,...,...
201,2023,2nd,Erling Haaland,Manchester City,357.0,32.78,Norway,CF,23,Premier League
202,2023,3rd,Kylian Mbappé,Paris Saint-Germain,270.0,24.79,France,CF,25,Ligue1
203,2024,1st,Rodri,Manchester City,1170.0,36.38,Spain,DM,28,Premier League
204,2024,2nd,Vinícius Júnior,Real Madrid,1129.0,35.11,Brazil,LW,24,La Liga
205,2024,3rd,Jude Bellingham,Real Madrid,917.0,28.51,England,AM,21,La Liga

    year champions_Winner    europaLeague_Winner
0   1956      Real Madrid                    NaN
1   1957      Real Madrid                    NaN
2   1958      Real Madrid                    NaN
3   1959      Real Madrid                    NaN
4   1960      Real Madrid                    NaN
..   ...              ...                    ...
64  2020    Bayern Monaco               Siviglia
65  2021          Chelsea             Villarreal
66  2022      Real Madrid  Eintracht Francoforte
67  2023  Manchester City               Siviglia
68  2024      Real Madrid               Atalanta

[69 rows x 3 columns]

,year,Mondiale_Winner,CoppaAsia_Winner,CoppaAfrica_Winner,Europeo_Winner,CoppaAmerica_Winner
0,1956,NaN,Corea del Sud,NaN,NaN,Uruguay
1,1957,NaN,NaN,Egitto,NaN,Argentina
2,1958,Brasile,NaN,NaN,NaN,NaN
3,1959,NaN,NaN,Rep. Araba Unita,NaN,Argentina
4,1959,NaN,NaN,Rep. Araba Unita,NaN,Uruguay
5,1960,NaN,Corea del Sud,NaN,Unione Sovietica,NaN
6,1962,Brasile,NaN,Etiopia,NaN,NaN
7,1963,NaN,NaN,Ghana,NaN,Bolivia
8,1964,NaN,Israele,NaN,Spagna,NaN
9,1965,NaN,NaN,Ghana,NaN,NaN
10,1966,Inghilterra,NaN,NaN,NaN,NaN
11,1967,NaN,NaN,NaN,NaN,Uruguay
12,1968,NaN,Iran,Congo-Kinshasa,Italia,NaN
13,1970,Brasile,NaN,Sudan,NaN,NaN
14,1972,NaN,Iran,Congo-Brazzaville,Germania Ovest,NaN
15,1974,Germania Ovest,NaN,Zaire,NaN,NaN
16,1975,NaN,NaN,NaN,NaN,Perù
17,1976,NaN,Iran,Marocco,Cecoslovacchia,NaN
18,1978,Argentina,NaN,Ghana,NaN,NaN
19,1979,NaN,NaN,NaN,NaN,Paraguay
20,1980,NaN,Kuwait,Nigeria,Germania Ovest,NaN
21,1982,Italia,NaN,Ghana,NaN,NaN
22,1983,NaN,NaN,NaN,NaN,Uruguay
23,1984,NaN,Arabia Saudita,Camerun,Francia,NaN
24,1986,Argentina,NaN,Egitto,NaN,NaN
25,1987,NaN,NaN,NaN,NaN,Uruguay
26,1988,NaN,Arabia Saudita,Camerun,Paesi Bassi,NaN
27,1989,NaN,NaN,NaN,NaN,Brasile
28,1990,Germania Ovest,NaN,Algeria,NaN,NaN
29,1991,NaN,NaN,NaN,NaN,Argentina
30,1992,NaN,Giappone,Costa d'Avorio,Danimarca,NaN
31,1993,NaN,NaN,NaN,NaN,Argentina
32,1994,Brasile,NaN,Nigeria,NaN,NaN
33,1995,NaN,NaN,NaN,NaN,Uruguay
34,1996,NaN,Arabia Saudita,Sudafrica,Germania,NaN
35,1997,NaN,NaN,NaN,NaN,Brasile
36,1998,Francia,NaN,Egitto,NaN,NaN
37,1999,NaN,NaN,NaN,NaN,Brasile
38,2000,NaN,Giappone,Camerun,Francia,NaN
39,2001,NaN,NaN,NaN,NaN,Colombia
40,2002,Brasile,NaN,Camerun,NaN,NaN
41,2004,NaN,Giappone,Tunisia,Grecia,Brasile
42,2006,Italia,NaN,Egitto,NaN,NaN
43,2007,NaN,Iraq,NaN,NaN,Brasile
44,2008,NaN,NaN,Egitto,Spagna,NaN
45,2010,Spagna,NaN,Egitto,NaN,NaN
46,2011,NaN,Giappone,NaN,NaN,Uruguay
47,2012,NaN,NaN,Zambia,Spagna,NaN
48,2013,NaN,NaN,Nigeria,NaN,NaN
49,2014,Germania,NaN,NaN,NaN,NaN
50,2015,NaN,Australia,Costa d'Avorio,NaN,Cile
51,2016,NaN,NaN,NaN,Portogallo,Cile
52,2017,NaN,NaN,Camerun,NaN,NaN
53,2018,Francia,NaN,NaN,NaN,NaN
54,2019,NaN,Qatar,Algeria,NaN,Brasile
55,2021,NaN,NaN,NaN,NaN,Argentina
56,2022,Argentina,NaN,NaN,NaN,NaN
57,2023,NaN,Qatar,NaN,NaN,NaN
58,2024,NaN,NaN,NaN,Spagna,Argentina

,year,serieA_Winner,coppaItalia_Winner,legue1_Winner,coppaFrancia_Winner,bundesliga_Winner,coppaGermania_Winner,laLiga_Winner,coppaSpagna_Winner,admiralDivision_Winner,...,prvaLiga_Winner,coppaSlovenia_Winner,ekstraklasa_Winner,coppaPolonia_Winner,proLeague_Winner,coppaBelgio_Winner,superliga_Winner,coppaDanimarca_Winner,scottishPremiership_Winner,coppaScozia_Winner
0,1956,Fiorentina,NaN,Nizza,Sedan-Torcy,Borussia Dortmund,Karlsruhe,Athletic Bilbao,Athletic Bilbao,Rapid Vienna,...,NaN,NaN,Legia Varsavia,Legia Varsavia,Anderlecht,Tournai,Aarhus,Frem,Rangers,Hearts
1,1957,Milan,NaN,Saint-Étienne,Tolosa,Borussia Dortmund,Bayern Monaco,Real Madrid,Barcellona,Rapid Vienna,...,NaN,NaN,Górnik Zabrze,ŁKS,Anversa,NaN,Aarhus,Aarhus,Rangers,Falkirk
2,1958,Juventus,Lazio,Stade Reims,Stade Reims,Schalke 04,Stoccarda,Real Madrid,Athletic Bilbao,Wiener SC,...,NaN,NaN,ŁKS,NaN,Standard Liegi,NaN,Vejle,Vejle,Hearts,Clyde
3,1959,Milan,Juventus,Nizza,Le Havre,Eintracht Francoforte,Schwarz-Weiß Essen,Barcellona,Barcellona,Wiener SC,...,NaN,NaN,Górnik Zabrze,NaN,Anderlecht,NaN,B 1909,Vejle,Rangers,St. Mirren
4,1960,Juventus,Juventus,Stade Reims,Monaco,Amburgo,Borussia M'gladbach,Barcellona,Atlético Madrid,Rapid Vienna,...,NaN,NaN,Ruch Chorzów,NaN,Lierse,NaN,Aarhus,Aarhus,Hearts,Rangers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,2020,Juventus,Napoli,Paris Saint-Germain,Paris Saint-Germain,Bayern Monaco,Bayern Monaco,Real Madrid,Real Sociedad,Salisburgo,...,Celje,NŠ Mura,Legia Varsavia,KS Cracovia,Club Bruges,Anversa,Midtjylland,SønderjyskE,Celtic,Celtic
66,2021,Inter,Juventus,Lilla,Paris Saint-Germain,Bayern Monaco,Borussia Dortmund,Atlético Madrid,Barcellona,Salisburgo,...,NŠ Mura,Olimpia Lubiana (2005),Legia Varsavia,Raków Częstochowa,Club Bruges,Genk,Brøndby,Randers,Rangers,St. Johnstone
67,2022,Milan,Inter,Paris Saint-Germain,Nantes,Bayern Monaco,RB Lipsia,Real Madrid,Betis,Salisburgo,...,NŠ Mura,Koper,Lech Poznań,Raków Częstochowa,Club Bruges,Gent,Copenaghen,Midtjylland,Celtic,Rangers
68,2023,Napoli,Inter,Paris Saint-Germain,Tolosa,Bayern Monaco,RB Lipsia,Barcellona,Real Madrid,Salisburgo,...,NŠ Mura,Olimpia Lubiana (2005),Raków Częstochowa,Legia Varsavia,Anversa,Anversa,Copenaghen,Copenaghen,Celtic,Celtic
69,2024,Inter,Juventus,Paris Saint-Germain,Paris Saint-Germain,Bayer Leverkusen,Bayer Leverkusen,Real Madrid,Athletic Bilbao,Sturm Graz,...,NŠ Mura,Rogaška,Jagiellonia,Wisła Cracovia,Club Bruges,Union Saint-Gilloise,Midtjylland,Silkeborg,Celtic,Celtic

In [5]:
df_competitions = pd.DataFrame(df_Champions_EuropaLeague)
df_competitions = pd.merge(df_competitions, df_CompetizioniNazionali, on='year', how='outer')
df_competitions = df_competitions.sort_values(by='year').reset_index(drop=True)

display(df_competitions)

,year,champions_Winner,europaLeague_Winner,Mondiale_Winner,CoppaAsia_Winner,CoppaAfrica_Winner,Europeo_Winner,CoppaAmerica_Winner
0,1956,Real Madrid,NaN,NaN,Corea del Sud,NaN,NaN,Uruguay
1,1957,Real Madrid,NaN,NaN,NaN,Egitto,NaN,Argentina
2,1958,Real Madrid,NaN,Brasile,NaN,NaN,NaN,NaN
3,1959,Real Madrid,NaN,NaN,NaN,Rep. Araba Unita,NaN,Argentina
4,1959,Real Madrid,NaN,NaN,NaN,Rep. Araba Unita,NaN,Uruguay
...,...,...,...,...,...,...,...,...
65,2020,Bayern Monaco,Siviglia,NaN,NaN,NaN,NaN,NaN
66,2021,Chelsea,Villarreal,NaN,NaN,NaN,NaN,Argentina
67,2022,Real Madrid,Eintracht Francoforte,Argentina,NaN,NaN,NaN,NaN
68,2023,Manchester City,Siviglia,NaN,Qatar,NaN,NaN,NaN
69,2024,Real Madrid,Atalanta,NaN,NaN,NaN,Spagna,Argentina

In [6]:
df_Unione =  pd.DataFrame(df_Champions_EuropaLeague)
df_Unione = pd.merge(df_Unione, df_CompetizioniNazionali, on='year', how='outer')
df_Unione = pd.merge(df_Unione, df_CompetizioniPerNazione, on='year', how='outer')
df_Unione = df_Unione.sort_values(by='year').reset_index(drop=True)

display(df_Unione)
df_Unione.to_csv('dfUnioneCoppe.csv', index=False)

,year,champions_Winner,europaLeague_Winner,Mondiale_Winner,CoppaAsia_Winner,CoppaAfrica_Winner,Europeo_Winner,CoppaAmerica_Winner,serieA_Winner,coppaItalia_Winner,...,prvaLiga_Winner,coppaSlovenia_Winner,ekstraklasa_Winner,coppaPolonia_Winner,proLeague_Winner,coppaBelgio_Winner,superliga_Winner,coppaDanimarca_Winner,scottishPremiership_Winner,coppaScozia_Winner
0,1956,Real Madrid,NaN,NaN,Corea del Sud,NaN,NaN,Uruguay,Fiorentina,NaN,...,NaN,NaN,Legia Varsavia,Legia Varsavia,Anderlecht,Tournai,Aarhus,Frem,Rangers,Hearts
1,1957,Real Madrid,NaN,NaN,NaN,Egitto,NaN,Argentina,Milan,NaN,...,NaN,NaN,Górnik Zabrze,ŁKS,Anversa,NaN,Aarhus,Aarhus,Rangers,Falkirk
2,1958,Real Madrid,NaN,Brasile,NaN,NaN,NaN,NaN,Juventus,Lazio,...,NaN,NaN,ŁKS,NaN,Standard Liegi,NaN,Vejle,Vejle,Hearts,Clyde
3,1959,Real Madrid,NaN,NaN,NaN,Rep. Araba Unita,NaN,Argentina,Milan,Juventus,...,NaN,NaN,Górnik Zabrze,NaN,Anderlecht,NaN,B 1909,Vejle,Rangers,St. Mirren
4,1959,Real Madrid,NaN,NaN,NaN,Rep. Araba Unita,NaN,Uruguay,Milan,Juventus,...,NaN,NaN,Górnik Zabrze,NaN,Anderlecht,NaN,B 1909,Vejle,Rangers,St. Mirren
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,2020,Bayern Monaco,Siviglia,NaN,NaN,NaN,NaN,NaN,Juventus,Napoli,...,Celje,NŠ Mura,Legia Varsavia,KS Cracovia,Club Bruges,Anversa,Midtjylland,SønderjyskE,Celtic,Celtic
67,2021,Chelsea,Villarreal,NaN,NaN,NaN,NaN,Argentina,Inter,Juventus,...,NŠ Mura,Olimpia Lubiana (2005),Legia Varsavia,Raków Częstochowa,Club Bruges,Genk,Brøndby,Randers,Rangers,St. Johnstone
68,2022,Real Madrid,Eintracht Francoforte,Argentina,NaN,NaN,NaN,NaN,Milan,Inter,...,NŠ Mura,Koper,Lech Poznań,Raków Częstochowa,Club Bruges,Gent,Copenaghen,Midtjylland,Celtic,Rangers
69,2023,Manchester City,Siviglia,NaN,Qatar,NaN,NaN,NaN,Napoli,Inter,...,NŠ Mura,Olimpia Lubiana (2005),Raków Częstochowa,Legia Varsavia,Anversa,Anversa,Copenaghen,Copenaghen,Celtic,Celtic
70,2024,Real Madrid,Atalanta,NaN,NaN,NaN,Spagna,Argentina,Inter,Juventus,...,NŠ Mura,Rogaška,Jagiellonia,Wisła Cracovia,Club Bruges,Union Saint-Gilloise,Midtjylland,Silkeborg,Celtic,Celtic